"""
build.py
--------
Reads  data/maven.json  →  generates  data/maven-data.js
Run:   py build.py
"""
import json, os, textwrap

SRC  = os.path.join("data", "maven.json")
DEST = os.path.join("data", "maven-data.js")

def to_markmap(node, depth=0):
    """Convert simple {text, children} tree → markmap {content, children, payload} tree."""
    return {
        "content": node["text"],
        "children": [to_markmap(c, depth + 1) for c in node.get("children", [])],
        "payload": {"fold": 1 if depth >= 1 else 0}
    }

def collect_explanations(node, acc):
    """Walk the tree and collect every node that has an 'explanation' field."""
    if "explanation" in node:
        acc[node["text"]] = node["explanation"]
    for c in node.get("children", []):
        collect_explanations(c, acc)

def collect_quizzes(node, acc):
    """Walk the tree and collect every node that has a 'quiz' field."""
    if "quiz" in node:
        acc[node["text"]] = node["quiz"]
    for c in node.get("children", []):
        collect_quizzes(c, acc)

def main():
    with open(SRC, encoding="utf-8") as f:
        data = json.load(f)

    meta = data["meta"]
    root = to_markmap(data["root"])

    explanations = {}
    collect_explanations(data["root"], explanations)

    quizzes = {}
    collect_quizzes(data["root"], quizzes)

    js = textwrap.dedent(f"""\
        // AUTO-GENERATED by build.py — edit maven.json then re-run build.py
        // Last built from: {SRC}

        var MAVEN_META = {json.dumps(meta, ensure_ascii=False, indent=2)};

        var MAVEN_ROOT = {json.dumps(root, ensure_ascii=False, indent=2)};

        var MAVEN_EXPLANATIONS = {json.dumps(explanations, ensure_ascii=False, indent=2)};

        var MAVEN_QUIZZES = {json.dumps(quizzes, ensure_ascii=False, indent=2)};
    """)

    with open(DEST, "w", encoding="utf-8") as f:
        f.write(js)

    topics = len(data["root"].get("children", []))
    exp_count = len(explanations)
    quiz_count = len(quizzes)
    print(f"Done! Built {DEST}  ({topics} top-level topics, {exp_count} explanations, {quiz_count} quizzes)")

if __name__ == "__main__":
    main()
